version: '3'

services:
  mongodb-primary:
    image: 'bitnami/mongodb:latest'
    environment:
      - MONGODB_ROOT_PASSWORD=adveniatRegnumTuum
      - MONGODB_USERNAME=my_user
      - MONGODB_PASSWORD=password123
      - MONGODB_DATABASE=my_database
    ports:
      - "27017:27017"
    volumes:
      - 'mongodb_master_data:/bitnami'

volumes:
  mongodb_master_data:
    driver: local